name: test core

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: download test file
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://raw.githubusercontent.com/jar-analyzer/test/refs/heads/main/javasec-1.15.jar -O javasec-1.15.jar
      - name: run maven test
        run: mvn test -Dtest=SpringCoreTest#testRun
      - name: clean test file
        run: rm -f javasec-1.15.jar